quarkus.rest-client.baserow.url=https://api.baserow.io
baserow.events-table-id=824717
baserow.registrations-table-id=824726
baserow.guests-table-id=824727
baserow.notifications-table-id=831451
baserow.token=21Jkk8NfgfPsLQXS7PG2bH1fNPOjq2Xe

quarkus.log.category."org.jboss.resteasy.reactive.client".level=DEBUG
quarkus.log.category."io.quarkus.rest.client.reactive".level=DEBUG
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=0