quarkus.rest-client.baserow.url=https://api.baserow.io

baserow.events.events-table-id=824717
baserow.events.registrations-table-id=824726
baserow.events.guests-table-id=824727
baserow.events.notifications-table-id=831451

baserow.coworking.guests-table-id=824729
baserow.coworking.notifications-table-id=831434
baserow.coworking.tariffs-table-id=824730
baserow.coworking.active-tariffs-table-id=831438
baserow.coworking.meeting-room-bookings-table-id=824738

baserow.token=21Jkk8NfgfPsLQXS7PG2bH1fNPOjq2Xe

quarkus.log.category."org.jboss.resteasy.reactive.client".level=DEBUG
quarkus.log.category."io.quarkus.rest.client.reactive".level=DEBUG
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=0