package com.lan.app.api.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    VALIDATION_ERROR,
    BUSINESS_CONFLICT,
    BASEROW_INCOMPLETE_ROW,
    BASEROW_UNAVAILABLE,
    INTERNAL_SERVER_ERROR
}